CREATE DATABASE IF NOT EXISTS DB205DWESProyectoTema4;

USE DB205DWESProyectoTema4;

CREATE TABLE IF NOT EXISTS T02_Departamento (
  T02_CodDepartamento VARCHAR(3) NOT NULL PRIMARY KEY,
  T02_DescDepartamento VARCHAR (255) NOT NULL,
  T02_FechaCreacionDepartamento DATETIME NOT NULL,
  T02_FechaBaja DATETIME,
  T02_VolumenNegocio FLOAT NOT NULL) ENGINE = INNODB;

CREATE USER IF NOT EXISTS 'user205DWESProyectoTema4'@'%' IDENTIFIED BY 'paso';

GRANT ALL PRIVILEGES ON DB205DWESProyectoTema4.* TO 'user205DWESProyectoTema4'@'%';




